### ISSUE TITLE
不定期的token失效

### ISSUE THREAD

**Issue by helloyou2012** [node-webot/co-wechat-api#18]
错误日志如下：

```
WeChatAPIError: invalid credential, access_token is invalid or not latest hint: [j0563vr23]
      at API.request (/xxxxx/node_modules/co-wechat-api/lib/api_common.js:122:17)
      at next (native)
      at exports.getTicket (/xxxxx/node_modules/co-wechat-api/lib/api_js.js:74:26)
      at next (native)
      at exports.ensureTicket (/xxxxx/node_modules/co-wechat-api/lib/api_js.js:160:26)
      at next (native)
      at exports.getJsConfig (/xxxxx/node_modules/co-wechat-api/lib/api_js.js:179:28)
      at next (native)
      at onFulfilled (/xxxxx/node_modules/co/index.js:65:19)
      at process._tickDomainCallback (node.js:409:9)
```

**Comment by nick-ma** [comment]
这种情况跟这个库没有直接关系。
请检查一下是否有别的地方同时请求了access token，导致微信服务器发放了新的access token给别人。

**Comment by helloyou2012** [comment]
了解了，别的地方请求token导致存在文件中的token过期。发生这种情况时，是否需要对过期的token更新下过期日期？

**Comment by nick-ma** [comment]
只要把token信息删除即可，api会自动帮你重新获取一个最新的。
