### ISSUE TITLE
不知道是什么错

### ISSUE THREAD

**Issue by Messilimeng** [node-webot/co-wechat-api#62]
/root/aasd/node_modules/co-wechat-api/lib/api_common.js:59
    this.getToken = getToken || async function () {
                                      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/51work/node_modules/co-wechat-api/index.js:3:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
/root/51work/node_modules/co-wechat-api/lib/api_common.js:59

**Comment by JacksonTian** [comment]
升级 node 版本至 8.x

**Comment by Messilimeng** [comment]
好的明白了

**Comment by MaxIsComing** [comment]
node_modules/_co-open-wechat-api@0.0.1@co-open-wechat-api/lib/api_common.js:97
    this.getComponentToken = getComponentToken || async function () {
                                                        ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)

**Comment by JacksonTian** [comment]
co-open-wechat-api 是什么模块？找对应的维护者

**Comment by liuyiji** [comment]
连接本地代码调试一下，


原始邮件
发件人:Jackson Tiannotifications@github.com
收件人:node-webot/co-wechat-apico-wechat-api@noreply.github.com
抄送:Subscribedsubscribed@noreply.github.com
发送时间:2018年6月29日(周五) 11:58
主题:Re: [node-webot/co-wechat-api] 不知道是什么错 (#62)


co-open-wechat-api 是什么模块？找对应的维护者

**Comment by MaxIsComing** [comment]
好~
